version: 2.1

workflows:
  test:
    jobs:
      - test:
          context:
            - CodeVideo
          filters:
            branches:
              only:
                - develop
  test_and_release:
    jobs:
      - test:
          context:
            - CodeVideo
          filters:
            branches:
              only:
                - main
      - release:
          context:
            - CodeVideo
          requires:
            - test

jobs:
  test:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107
    steps:
      - checkout
      - run:
          name: Install dependencies (root)
          command: npm install
      - run:
          name: Install dependencies (example app)
          command: cd example && npm install
      - run:
          name: Copy src to example app
          command: cp -Rf src example/src
      - run:
          name: Build example app
          command: cd example && npm run build
      - run:
          name: Copy serve config to build
          command: cp serve.json example/build/serve.json
      - run:
          name: Run Tests (CI Mode)
          command: npm run test-ci
  release:
    docker:
      - image: node:18-alpine
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: |
          version_string=$(grep '"version":' package.json)
          version=$(echo "$version_string" | sed -E 's/.*"([^"]+)".*/\1/')
          git checkout -b release
          git add -A
          git tag -a $version commit -m "Release $new_version - built by Circle CI"
          git push origin release
      - run: npm publish