version: 2.1

workflows:
  test:
    jobs:
      - test:
          context:
            - codevideo
          filters:
            branches:
              only:
                - develop
  test_and_release:
    jobs:
      - test:
          context:
            - codevideo
          filters:
            branches:
              only:
                - main
      - release:
          context:
            - codevideo
          requires:
            - test
  publish:
    jobs:
      - publish:
          context:
            - codevideo
          filters:
            branches:
              only:
                - release

jobs:
  test:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "3b:48:63:e6:ea:57:a5:a1:06:f8:74:87:31:b4:67:86"
      - run:
          name: Install dependencies (root)
          command: npm install
      - run:
          name: Install dependencies (example app)
          command: cd example && npm install
      - run:
          name: Copy src to example app
          command: cp -Rf src example/src
      - run:
          name: Build example app
          command: cd example && npm run build
      - run:
          name: Copy serve config to build
          command: cp serve.json example/build/serve.json
      - run:
          name: Run Tests (CI Mode)
          command: npm run test-ci
      - run:
          name: Merge to main
          command: |
            git config --global user.email $GIT_USER_EMAIL
            git config --global user.name $GIT_USER_NAME
            git checkout main
            git add -A
            git commit -m "Auto merge to main by Circle CI"
            git push origin main
  release:
    docker:
      - image: node:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "3b:48:63:e6:ea:57:a5:a1:06:f8:74:87:31:b4:67:86"
      - run: npm install
      - run: npm run build
      - run: |
          version_string=$(grep '"version":' package.json)
          version=$(echo "$version_string" | sed -E 's/.*"([^"]+)".*/\1/')
          git config --global user.email $GIT_USER_EMAIL
          git config --global user.name $GIT_USER_NAME
          git checkout release
          git add -A
          git tag -a $version commit -m "Release $new_version - built by Circle CI"
          git push origin release
  publish:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm publish