version: 2.1

workflows:
  test:
    jobs:
      - test:
          context:
            - codevideo
          filters:
            branches:
              only:
                - develop
  release:
    jobs:
      - release:
          context:
            - codevideo
          filters:
            branches:
              only:
                - main
  publish:
    jobs:
      - publish:
          context:
            - codevideo
          filters:
            branches:
              only:
                - release

jobs:
  test:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "0e:de:f3:e5:2d:85:e2:7d:3b:d3:70:af:e9:db:e6:3a"
      - run:
          name: Install dependencies (root)
          command: npm install
      - run:
          name: Install dependencies (example app)
          command: cd example && npm install
      - run:
          name: Copy src to example app
          command: cp -Rf src example/src
      - run:
          name: Build example app
          command: cd example && npm run build
      - run:
          name: Copy serve config to build
          command: cp serve.json example/build/serve.json
      - run:
          name: Run Tests (CI Mode)
          command: npm run test-ci
      - run:
          name: Merge to main branch
          command: |
            git config --global user.email $GIT_USER_EMAIL
            git config --global user.name $GIT_USER_NAME
            git checkout main
            git merge develop
            git commit -m "Auto merge from develop to main by Circle CI"
            git push origin main
  release:
    docker:
      - image: node:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "0e:de:f3:e5:2d:85:e2:7d:3b:d3:70:af:e9:db:e6:3a"
      - run: 
          name: Install dependencies (npm install)
          command: npm install
      - run: 
          name: Build distribution version (npm run build)
          command: npm run build
      - run: 
          name: Merge to release branch with new version as git tag
          command: |
            version_string=$(grep '"version":' package.json)
            version=$(echo "$version_string" | sed -E 's/.*"([^"]+)".*/\1/')
            git config --global user.email $GIT_USER_EMAIL
            git config --global user.name $GIT_USER_NAME
            git checkout release
            git merge main
            git tag -a $version 
            git commit -m "Release $new_version: Auto merge from main to release by Circle CI"
            git push origin release
  publish:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Add npm registry credentials (uses NPM_USERNAME, NPM_PASSWORD, and NPM_EMAIL from context)
          command: npm adduser --registry=https://registry.npmjs.org/ --always-auth=true
      - run:
          name: Publish with npm (npm publish --access public)
          command: npm publish --access public